<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit82c6ea9de6b39550e679b7b779f04b0a
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'Psr\\Log\\' => 8,
        ),
        'M' => 
        array (
            'Monolog\\' => 8,
        ),
        5 => 
        array (
            '5511934424010\\Meuprimeiroprojetophpusandocomposer\\' => 50,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Psr\\Log\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/log/src',
        ),
        'Monolog\\' => 
        array (
            0 => __DIR__ . '/..' . '/monolog/monolog/src/Monolog',
        ),
        '5511934424010\\Meuprimeiroprojetophpusandocomposer\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit82c6ea9de6b39550e679b7b779f04b0a::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit82c6ea9de6b39550e679b7b779f04b0a::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit82c6ea9de6b39550e679b7b779f04b0a::$classMap;

        }, null, ClassLoader::class);
    }
}
